name = "claude-relay-unified"
compatibility_date = "2025-08-10"
main = "src/index.ts"

[vars]
NODE_ENV = "production"

[[kv_namespaces]]
binding = "CLAUDE_RELAY_ADMIN_KV"
id = "3705d309d76d4d33a4ba39ab6d477dcd"

[assets]
directory = "../frontend/.output/public"
